name: Publish Package

on:
    pull_request:
        types: [closed]
        branches:
            - main

permissions:
    contents: write
    packages: write
    pull-requests: write
    actions: write
    deployments: write
    statuses: write

jobs:
    publish:
        if: github.event.pull_request.merged == true # PR이 merge 됐을 때만 실행
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: yarn install

            - name: Build
              run: yarn build:core

            - name: Semantic Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              working-directory: ./core
              run: npx semantic-release --debug --force-publish
